import "~/styles/globals.css";

import Link from "next/link";
import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Fidder Family Weight Loss Tracker",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const pathname = "/";

  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="gradient-purple min-h-screen p-5">
        <div className="mx-auto max-w-7xl overflow-hidden rounded-2xl bg-white shadow-2xl">
          <div className="gradient-blue p-8 text-center text-white">
            <h1 className="mb-2 text-5xl font-light">
              Family Weight Loss Tracker
            </h1>
            <p className="text-lg opacity-90">
              Track progress, stay motivated, achieve goals together
            </p>
          </div>
          <div className="flex border-b border-gray-200 bg-gray-100">
            {[
              { id: "dashboard", link: "/", label: "Dashboard" },
              { id: "data-entry", link: "/data-entry", label: "Data Entry" },
              { id: "charts", link: "/charts", label: "Charts" },
              { id: "goals", link: "/goals", label: "Goals" },
            ].map((tab) => (
              <Link
                key={tab.id}
                href={tab.link}
                className={`flex-1 px-5 py-4 font-medium transition-all ${pathname === tab.link ? "border-b-4 border-blue-400 bg-white text-blue-400" : "bg-transparent text-gray-600 hover:bg-gray-200"}`}
              >
                {tab.label}
              </Link>
            ))}
          </div>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </div>
      </body>
    </html>
  );
}
