import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <div>
          <div className="flex h-full min-h-screen w-full flex-1 flex-col">
            <div className="flex h-full min-h-screen w-full flex-1 grow flex-col">
              <div>
                <div className="relative flex-1 grow">
                  <TRPCReactProvider>{children}</TRPCReactProvider>
                </div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
