import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Link from "next/link";

import TabLayout from "./_components/TabLayout";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Fidder Family Weight Loss Tracker",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="gradient-purple min-h-screen p-5">
        <div className="mx-auto max-w-7xl overflow-hidden rounded-2xl bg-white shadow-2xl">
          <div className="gradient-blue p-8 text-center text-white">
            <h1 className="mb-2 text-5xl font-light">
              Family Weight Loss Tracker
            </h1>

            <p className="text-lg opacity-90">
              Track progress, stay motivated, achieve goals together
            </p>
            <div className="flex items-center justify-center">
              <Link
                href="/sign-up"
                className="mx-4 rounded-lg bg-gray-100 px-6 py-2 text-gray-700 hover:bg-gray-200"
              >
                Sign Up
              </Link>
              <Link
                href="/login"
                className="mx-4 rounded-lg bg-green-600 px-6 py-2 text-gray-50 hover:bg-green-700"
              >
                Log In<span aria-hidden="true">&rarr;</span>
              </Link>
            </div>
          </div>

          <TabLayout />
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </div>
      </body>
    </html>
  );
}
